### ISSUE TITLE
Script suggestions ?

### ISSUE THREAD

**Issue by shodanx2** [alterNERDtive/elite-scripts#11]
Hi,

I am curious if the following information could be obtained through scripting

Current remaining 
hull hit points
shield hit point
pip distribution weapons/sys/engine

current orientation vector of ship
orientation vector to next star in route
orientation vector to $name_of_star

list of radar target
ship name of currently selected target
(other information of) currently selected target
IFF status of currently selected target
orientation vection of currently selected target

fuel remaining in fuel tank
bounty values

thanks !

**Comment by alterNERDtive** [comment]
Some caveats first:

- I have not played the game in about 3y.
- Because of that, I might misremember things.
- The scope of these scripts is interfacing with 3ʳᵈ party sites, not with game data.

> I am curious if the following information could be obtained through scripting

Generally there are 3 ways to get data from your game client:

1. Parsing the journal or the net log (if you don’t know what the net log is, you probably won’t need it).
2. Reading the status files the game puts next to the journal files.
3. Accessing game memory.

The first 2 are fine and intended by Frontier for you to grab data from. Point 3 will probably count as cheating, though knowing Frontier’s “anti cheat” it’s probably not an issue in practice. It is way more annoying to deal with, though.

As I said above, none of this is in scope for the scripts in this repo. Personally I used a combination of [VoiceAttack](https://voiceattack.com) and [EDDI](https://github.com/EDCD/EDDI) to get the data and act on it. Incidentally, these scripts were made to supplement that (see [my VA profiles](https://alternerdtive.github.io/VoiceAttack-profiles/) for reference) and were in the process of being converted to VoiceAttack plugins when I stopped playing the game and developing this stuff.

You can find more information on journal events e.g. in EDDI’s wiki on github.

> Current remaining
> hull hit points
> shield hit point

AFAI remember, there are journal events every now and then reporting changed hull/shield state. They are not following any regular intervals or damage thresholds and are pretty useless. Also IIRC that was in percent, not absolute hull points. The net log _might_ have more info.

> pip distribution weapons/sys/engine

Yes, that’s in the status file.

> current orientation vector of ship

I _think_ that is only a thing if you are currently in planetary flight, and then it’s obviously relative to the surface.

> orientation vector to next star in route
> orientation vector to $name_of_star

No, and acting on that in any automated way will _definitely_ count as cheating (e.g. an auto pilot).

> list of radar target

No.

> ship name of currently selected target
> (other information of) currently selected target
> IFF status of currently selected target

There are journal events for targeting and subtargeting that contain all kinds of information.

> orientation vection of currently selected target

No.

> fuel remaining in fuel tank

Yes, in the status file. Additionally there is at least a “low fuel” event in the journal, but I don’t remember what the threshold is.

> bounty values

Of your target? Might be in the target/scan event (_after_ scanning them for bounties, obviously).

**Comment by shodanx2** [comment]
Thank you for the pointers, much appreciated !
